name: Bug Report
description: Report a problem
labels: ['triage']
body:
  - type: markdown
    attributes:
      value: '## Description'

  - type: textarea
    id: summary
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: markdown
    attributes:
      value: '## Desktop'

  - type: dropdown
    id: gnome
    attributes:
      label: GNOME Version
      options:
        - 43
        - 44
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: gnome-other
    attributes:
      label: Other Version
      placeholder: 44.beta, 44.1, ...
    validations:
      required: false

  - type: input
    id: distribution
    attributes:
      label: Operating System
      placeholder: Ubuntu 22.10, Fedora 37, Arch, ...
    validations:
      required: true

  - type: markdown
    attributes:
      value: '## Extension'

  - type: dropdown
    id: source
    attributes:
      label: Installed from
      options:
        - Nightly ZIP
        - Built from source
        - GNOME Extensions
        - Distribution Package
        - Other
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: >
        What version of the project are you running?
      options:
        - 1.alpha
        - main
    validations:
      required: true

  - type: markdown
    attributes:
      value: '## Additional Information'

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: >
        Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >
        Please attach any relevant screenshots or screencasts that can help
        demonstrate the problem.
      placeholder: >
        Attach files by dragging & dropping or copying & pasting them.
